- name: Create 'solr' user
  user:
    name: solr
    state: present

- name: Download Solr archive
  get_url:
    url: https://archive.apache.org/dist/lucene/solr/7.7.1/solr-7.7.1.tgz
    dest: /tmp/solr-7.7.1.tgz

- name: Extract install_solr_service.sh
  ansible.builtin.unarchive:
    src: /tmp/solr-7.7.1.tgz
    dest: /tmp/
    remote_src: yes

- name: Install required packages
  dnf:
    name:
      - lsof
      - java-1.8.0-openjdk
    state: present
  
- name: Run install_solr_service.sh
  shell: /tmp/solr-7.7.1/bin/install_solr_service.sh /tmp/solr-7.7.1.tgz -f -n
  args:
    executable: /bin/bash
    creates: /etc/init.d/solr

- name: Ensure solr is running
  ansible.builtin.service:
    name: solr
    state: started

- name: Check the Daisy core does not exist
  command: "curl -sI http://localhost:8983/api/cores/daisy"
  register: solr_core_exists

- name: Create Solr core 'daisy' if it does not exist
  when: "'HTTP/1.1 200 OK' not in solr_core_exists.stdout"
  shell: /opt/solr-7.7.1/bin/solr create_core -c daisy
  args:
    executable: /bin/bash
  become_method: community.general.sudosu
  become_user: solr

- name: Copy schema.xml
  copy:
    src: /home/{{ daisy_user }}/daisy/docker/solr/schema.xml
    remote_src: true
    dest: /var/solr/data/daisy/conf/

- name: Copy solrconfig.xml
  copy:
    src: /home/{{ daisy_user }}/daisy/docker/solr/solrconfig.xml
    remote_src: true
    dest: /var/solr/data/daisy/conf/

- name: Copy currency.xml
  copy:
    src: /home/{{ daisy_user }}/daisy/docker/solr/currency.xml
    remote_src: true
    dest: /var/solr/data/daisy/conf/

- name: Copy elevate.xml
  copy:
    src: /home/{{ daisy_user }}/daisy/docker/solr/elevate.xml
    remote_src: true
    dest: /var/solr/data/daisy/conf/

- name: Change ownership to solr:users
  ansible.builtin.file:
    path: /var/solr
    state: directory
    recurse: yes
    owner: solr
    group: users
    mode: '775'

