FROM ghcr.io/elixir-luxembourg/daisy:master

# Copy the project files
COPY . /code/
RUN chown -R 1000:1000 /code

WORKDIR /code
USER 1000:1000
RUN python manage.py collectstatic --noinput

USER root
RUN rm -rf /code/web/static
