services:
    # web app
    web:
        build: .
        expose:
            - '5000'
        environment:
            - DJANGO_SETTINGS_MODULE=elixir_daisy.settings_compose
            - TZ=${TZ:-UTC}
        volumes:
            - statics:/static
            - solrdata:/solr
            - .:/code
        networks:
            - daisy_network
        depends_on:
            - db
            - solr
            - mq
        command: gunicorn --reload -w 2 -b :5000 --pid /run/gunicorn.pid elixir_daisy.wsgi
    # database
    db:
        image: postgres:10.1
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD:-daisy}
            POSTGRES_USER: ${DB_USER:-daisy}
            POSTGRES_DB: ${DB_NAME:-daisy}
            TZ: ${TZ:-UTC}
        networks:
            - daisy_network
        volumes:
            - pgdata:/var/lib/postgresql/data
    # web server frontend
    nginx:
        build: ./docker/nginx
        restart: unless-stopped
        environment:
            - TZ=${TZ:-UTC}
        volumes:
            - statics:/public/static:ro
        ports:
            - '80:80'
            - '443:443'
        networks:
            - daisy_network
        depends_on:
            - web
    # FTS db
    solr:
        build: ./docker/solr
        restart: unless-stopped
        environment:
            - TZ=${TZ:-UTC}
        ports:
            - "8983:8983"
        networks:
            - daisy_network
        volumes:
            - solrdata:/opt/solr/server/solr
    # rabbit mq
    mq:
        image: rabbitmq:3.9-management-alpine
        restart: unless-stopped
        environment:
            - TZ=${TZ:-UTC}
        networks:
            - daisy_network
        ports:
            - "15672:15672"
            - "5672:5672"
    # task monitoring
    flower:
        image: mher/flower:0.9.7
        command: --broker=amqp://guest:guest@mq:5672// --broker_api=http://guest:guest@mq:15672/api/
        environment:
            - TZ=${TZ:-UTC}
        ports:
            - "5555:5555"
        restart: unless-stopped
        networks:
            - daisy_network
        depends_on:
            - mq
    # task runner
    worker:
        build: .
        environment:
            - DJANGO_SETTINGS_MODULE=elixir_daisy.settings_compose
            - TZ=${TZ:-UTC}
        volumes:
            - .:/code
        depends_on:
            - db
            - mq
        restart: unless-stopped
        networks:
            - daisy_network
        command: "celery -A elixir_daisy.celery_app worker --loglevel=DEBUG"
    # celery beat
    beat:
        build: .
        environment:
            - DJANGO_SETTINGS_MODULE=elixir_daisy.settings_compose
            - TZ=${TZ:-UTC}
        volumes:
            - .:/code
        depends_on:
            - db
            - mq
        networks:
            - daisy_network
        command: "celery -A elixir_daisy beat --loglevel=DEBUG --pidfile= --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    # Backup service
    backup:
        image: alpine:3.20.3
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=${DB_NAME:-daisy}
            - DB_USER=${DB_USER:-daisy}
            - DB_PASSWORD=${DB_PASSWORD:-daisy}
            - BACKUP_DIR=/backups
            - MEDIA_DIR=/code/documents
            - SOLR_PORT=8983
            - RABBITMQ_MANAGEMENT_PORT=${RABBITMQ_MANAGEMENT_PORT:-15672}
            - BACKUP_VOLUME=${BACKUP_VOLUME:-../backups}
            - TZ=${TZ:-UTC}
        volumes:
            - ${BACKUP_VOLUME:-../backups}:/backups
            - .:/code
            - /var/run/docker.sock:/var/run/docker.sock
        working_dir: /code
        depends_on:
            - db
        networks:
            - daisy_network
        entrypoint: >
            sh -c "apk add --no-cache docker-cli docker-compose postgresql-client lsof &&
               chmod +x /code/scripts/db.sh &&
               tail -f /dev/null"

volumes:
    pgdata:
    statics:
    solrdata:
    backups:

networks:
  daisy_network:
    driver: bridge
