# Generated by Django 2.1.9 on 2019-07-15 08:42

import core.models.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalBasis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Justifications on why this legal basis is chosen.",
                        max_length=255,
                        null=True,
                        verbose_name="Remarks",
                    ),
                ),
                (
                    "data_declarations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The scope of this legal basis definition. Leave this field empty if the legal basis applies to entire dataset.",
                        related_name="processed_with_legal_bases",
                        to="core.DataDeclaration",
                        verbose_name="Applies to",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_basis_definitions",
                        to="core.Dataset",
                    ),
                ),
            ],
            options={
                "ordering": ["added"],
                "get_latest_by": "added",
            },
        ),
        migrations.CreateModel(
            name="LegalBasisType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    core.models.utils.TextFieldWithInputWidget(
                        max_length=20, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "name",
                    core.models.utils.TextFieldWithInputWidget(
                        max_length=120, unique=True, verbose_name="Name"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "get_latest_by": "added",
            },
        ),
        migrations.CreateModel(
            name="PersonalDataType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    core.models.utils.TextFieldWithInputWidget(
                        max_length=20, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "name",
                    core.models.utils.TextFieldWithInputWidget(
                        max_length=120, unique=True, verbose_name="Name"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "get_latest_by": "added",
            },
        ),
        migrations.AddField(
            model_name="legalbasis",
            name="legal_basis_types",
            field=models.ManyToManyField(
                help_text="Under which legal bases for data processing, you can select more than one.",
                related_name="legal_basis_definitions",
                to="core.LegalBasisType",
                verbose_name="Legal Bases",
            ),
        ),
        migrations.AddField(
            model_name="legalbasis",
            name="personal_data_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="What categories of personal data is processed, you can select more than one.",
                related_name="legal_basis_definitions",
                to="core.PersonalDataType",
                verbose_name="Categories of personal data",
            ),
        ),
    ]
