# Generated by Django 2.1.9 on 2019-07-19 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_partner_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="data_declarations",
            field=models.ManyToManyField(
                blank=True,
                help_text="The scope of this transfer. Leave this empty if the all data declarations were transferred.",
                related_name="share_records",
                to="core.DataDeclaration",
                verbose_name="Transfers",
            ),
        ),
        migrations.AlterField(
            model_name="datadeclaration",
            name="comments",
            field=models.TextField(
                blank=True,
                help_text="Please provide any remarks on the source and nature of data.",
                null=True,
                verbose_name="Remarks on data source",
            ),
        ),
        migrations.AlterField(
            model_name="datadeclaration",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                help_text="The Contract that ensures the legal receipt, keeping and analysis of this data.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_declarations",
                to="core.Contract",
            ),
        ),
        migrations.AlterField(
            model_name="datadeclaration",
            name="data_declarations_parents",
            field=models.ManyToManyField(
                blank=True,
                help_text="If this data declaration is based on or derived from an earlier data declaration, then select ancestor data declaration.",
                related_name="data_declarations_derivated",
                to="core.DataDeclaration",
                verbose_name="Derived/re-used from:",
            ),
        ),
        migrations.AlterField(
            model_name="datadeclaration",
            name="data_types_notes",
            field=models.TextField(
                blank=True,
                help_text="Remarks on data types, especially if dealing with a data type not present in the predefined list.",
                null=True,
                verbose_name="Remarks on data types",
            ),
        ),
        migrations.AlterField(
            model_name="datadeclaration",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="The Partner/Institute that have provided this data.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_declarations",
                to="core.Partner",
            ),
        ),
    ]
