# Generated by Django 2.1.10 on 2019-08-02 08:11

import core.models.user
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190731_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=enumchoicefield.fields.EnumChoiceField(default=core.models.user.UserSource(2), enum_class=core.models.user.UserSource, max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
