# Generated by Django 2.2.10 on 2021-01-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200130_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='userestriction',
            name='use_restriction_rule',
            field=models.TextField(choices=[('CONSTRAINTS', 'CONSTRAINTS'), ('NO_CONSTRAINTS', 'NO_CONSTRAINTS'), ('FORBIDDEN', 'FORBIDDEN')], default='NO_CONSTRAINTS', max_length=64, verbose_name='Does the rule forbid (FORBIDDEN), constraint (CONSTRAINTS) or have no constraints (NO_CONSTRAINTS)?'),
        ),
    ]
