# Generated by Django 2.2.20 on 2021-05-14 20:22

import core.models.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210514_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', core.models.utils.TextFieldWithInputWidget(max_length=128, verbose_name='Name of the type of the document')),
            ],
            options={
                'ordering': ['added'],
                'get_latest_by': 'added',
            },
        ),
        migrations.RemoveField(
            model_name='share',
            name='grant_expires_on',
        ),
        migrations.AlterField(
            model_name='share',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='The contract that provides the legal basis for this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares', to='core.Contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='share',
            name='granted_on',
            field=models.DateField(blank=True, help_text='The date on which the data event occured.', null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='share',
            name='partner',
            field=models.ForeignKey(help_text='The Partner involved in the data event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares', to='core.Partner', verbose_name='Involved partner'),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_notes',
            field=models.TextField(blank=True, help_text='Please state here any remarks e.g. safeguards, technical measures.', max_length=255, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='share',
            name='data_log_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DataLogType', verbose_name='Logbook entry category.'),
        ),
    ]
