# Generated by Django 2.2.20 on 2021-05-18 12:58

from django.db import migrations
from core.management.commands.load_initial_data import Command as load_init_data_cmd


class Migration(migrations.Migration):
    
    def create_log_types(apps, schema_editor):
        load_command = load_init_data_cmd()
        load_command.create_log_types()

    dependencies = [
        ('core', '0017_auto_20210518_1458'),
    ]

    operations = [
        migrations.RunPython(create_log_types),
    ]
