# Generated by Django 2.2.20 on 2021-06-16 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_load_datalogtype_fixtures'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User that has the access'),
        ),
        migrations.AlterField(
            model_name='access',
            name='defined_on_locations',
            field=models.ManyToManyField(blank=True, help_text='The dataset locations on which access is defined.', null=True, related_name='accesses', to='core.DataLocation', verbose_name='Data Locations'),
        ),
    ]
