# Generated by Django 2.2.20 on 2021-06-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_load_datalogtype_fixtures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userestriction',
            name='use_restriction_rule',
            field=models.TextField(choices=[('OBLIGATION', 'OBLIGATION'), ('PERMISSION', 'PERMISSION'), ('PROHIBITION', 'PROHIBITION')], default='PROHIBITION', max_length=64, verbose_name='Use Restriction Rule'),
        ),
    ]
