# Generated by Django 2.2.20 on 2021-06-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210616_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oidc_id',
            field=models.CharField(blank=True, help_text="Internal user identifier coming from OIDC's IdP", max_length=64, null=True, verbose_name='OIDC user identifier'),
        ),
    ]
