# Generated by Django 2.2.20 on 2021-06-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210622_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userestriction',
            name='use_restriction_rule',
            field=models.TextField(choices=[('OBLIGATION', 'OBLIGATION'), ('PERMISSION', 'PERMISSION'), ('PROHIBITION', 'PROHIBITION'), ('CONSTRAINED_PERMISSION', 'CONSTRAINED_PERMISSION')], default='PROHIBITION', max_length=64, verbose_name='Use Restriction Rule'),
        ),
    ]
