# Generated by Django 2.2.20 on 2021-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210622_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='domain_type',
            field=models.TextField(choices=[('not_specified', 'Not Specified'), ('agreement', 'Agreement'), ('ethics_approval', 'Ethics Approval'), ('consent_form', 'Consent Form'), ('subject_informationsheet', 'Subject InformationSheet'), ('project_proposal', 'Project Proposal'), ('dpia', 'DPIA'), ('other', 'Other')], default='not_specified', verbose_name='Domain Type'),
        ),
    ]
