# Generated by Django 2.2.24 on 2021-10-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_datadec_title_unq_constraint'),
    ]

    def set_flag_for_local_custodians(apps, schema_editor):
        classes = ['Dataset', 'Project']
        for klass in classes:
            Dataset = apps.get_model('core', klass)
            for dataset in Dataset.objects.all():
                for custodian in dataset.local_custodians.all():
                    custodian.should_receive_email_reports = True
                    custodian.save()

    def remove_flags_for_local_custodians(apps, schema_editor):
        Users = apps.get_model('core', 'User')
        for user in Users.objects.all():
            user.should_receive_email_reports = False
            user.save()

    operations = [
        migrations.AddField(
            model_name='user',
            name='should_receive_email_reports',
            field=models.BooleanField(default=False, help_text='Should the user receive periodic email reports?', verbose_name='Should receive email reports'),
        ),

        migrations.RunPython(set_flag_for_local_custodians, remove_flags_for_local_custodians),
    ]
