# Generated by Django 2.2.24 on 2021-10-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_datadec_title_unq_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='should_receive_email_reports',
            field=models.BooleanField(default=False, help_text='Should the user receive periodic email reports?', verbose_name='Should receive email reports'),
        ),
    ]
