# Generated by Django 2.2.24 on 2021-10-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_datadec_title_unq_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='scientific_metadata',
            field=models.TextField(default='{}', verbose_name='Additional scientific metadata (in JSON format)'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='scientific_metadata',
            field=models.TextField(default='{}', verbose_name='Additional scientific metadata (in JSON format)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='scientific_metadata',
            field=models.TextField(default='{}', verbose_name='Additional scientific metadata (in JSON format)'),
        ),
        migrations.AddField(
            model_name='project',
            name='scientific_metadata',
            field=models.TextField(default='{}', verbose_name='Additional scientific metadata (in JSON format)'),
        ),
        migrations.AlterField(
            model_name='userestriction',
            name='use_restriction_rule',
            field=models.TextField(choices=[('PROHIBITION', 'PROHIBITION'), ('OBLIGATION', 'OBLIGATION'), ('PERMISSION', 'PERMISSION'), ('CONSTRAINED_PERMISSION', 'CONSTRAINED_PERMISSION')], default='PROHIBITION', max_length=64, verbose_name='Use Restriction Rule'),
        ),
    ]
