# Generated by Django 2.2.28 on 2022-06-15 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_auto_20220517_1622"),
        ("core", "0025_auto_20220309_1803"),
    ]

    operations = []
