# Generated by Django 2.2.28 on 2022-06-15 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_merge_20220615_1501"),
        ("core", "0026_auto_20220429_0848"),
    ]

    operations = []
