# Generated by Django 2.2.28 on 2022-06-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20220615_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='should_receive_email_reports',
            field=models.BooleanField(default=False, help_text='Should the user receive periodic email reports?', verbose_name='Should receive email reports'),
        ),
    ]
