# Generated by Django 3.2.19 on 2023-05-15 11:53

import core.models.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20230508_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohort',
            old_name='is_published',
            new_name='_is_published',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='is_published',
            new_name='_is_published',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_published',
        ),
    ]
