# Generated by Django 3.2.20 on 2023-11-08 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_auto_20230515_1353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Use either `contact` or `user`",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accesses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User that has the access",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="local_custodians",
            field=models.ManyToManyField(
                help_text="Custodians are the local responsibles for the project. This list must include a PI.",
                related_name="project_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Local custodians",
            ),
        ),
    ]
