# Generated by Django 3.2 on 2023-08-07 12:31

import core.models.access
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20230515_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=core.models.access.StatusChoices(1), enum_class=core.models.access.StatusChoices, help_text='The status of the Access', max_length=24),
        ),
    ]
