# Generated by Django 3.2.23 on 2024-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_use_restriction_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="elu_accession",
            field=models.CharField(
                blank=True,
                help_text="Unique persistent identifier of the record.",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Accession number",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="elu_accession",
            field=models.CharField(
                blank=True,
                help_text="Unique persistent identifier of the record.",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Accession number",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="elu_accession",
            field=models.CharField(
                blank=True,
                help_text="Unique persistent identifier of the record.",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Accession number",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="elu_accession",
            field=models.CharField(
                blank=True,
                help_text="Unique persistent identifier of the record.",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Accession number",
            ),
        ),
    ]
