# Generated by Django 3.2.23 on 2024-10-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_auto_20240924_1020"),
    ]

    operations = [
        migrations.AddField(
            model_name="access",
            name="application_external_id",
            field=models.CharField(
                blank=True,
                help_text="REMS application external ID.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="access",
            name="application_id",
            field=models.IntegerField(
                blank=True, help_text="REMS application ID.", null=True
            ),
        ),
    ]
