# Generated by Django 3.2.23 on 2025-02-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_auto_20241018_1733"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exposure",
            options={},
        ),
        migrations.AddField(
            model_name="exposure",
            name="deprecated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exposure",
            name="deprecation_reason",
            field=models.TextField(
                blank=True, help_text="Reason for deprecating this exposure", null=True
            ),
        ),
        migrations.AddField(
            model_name="exposure",
            name="is_deprecated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="exposure",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deprecated", False)),
                fields=("dataset", "endpoint"),
                name="unique_active_dataset_endpoint",
            ),
        ),
    ]
