# Generated by Django 3.2.23 on 2025-06-17 14:54

from django.db import migrations, models


def populate_contract_names(apps, schema_editor):
    from core.models import Contract

    for contract in Contract.objects.all():
        contract.name = contract.short_name()
        contract.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_auto_20250219_1834"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Select a meaningful name for your contract",
                max_length=200,
                null=True,
                verbose_name="Short name",
            ),
        ),
        migrations.RunPython(
            populate_contract_names, reverse_code=migrations.RunPython.noop
        ),
    ]
