# Generated by Django 3.2.23 on 2025-06-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_auto_20250219_1834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerrole",
            name="contacts",
            field=models.ManyToManyField(
                help_text="Add contact persons representing this partner in the contract.",
                related_name="partners_roles",
                to="core.Contact",
                verbose_name="Contacts",
            ),
        ),
        migrations.AlterField(
            model_name="partnerrole",
            name="contract",
            field=models.ForeignKey(
                help_text="The contract agreement this partner role belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partners_roles",
                to="core.contract",
                verbose_name="Contract",
            ),
        ),
        migrations.AlterField(
            model_name="partnerrole",
            name="partner",
            field=models.ForeignKey(
                help_text="Select the partner organisation involved in this contract.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partners_roles",
                to="core.partner",
                verbose_name="Partner",
            ),
        ),
        migrations.AlterField(
            model_name="partnerrole",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Role of the partner in the contract (e.g. GDPR role).",
                related_name="partners_roles",
                to="core.GDPRRole",
                verbose_name="Roles",
            ),
        ),
    ]
