# Generated by Django 3.2.23 on 2025-06-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_auto_20250617_1512"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Select a meaningful name for your contract",
                max_length=200,
                null=True,
                verbose_name="Short name",
            ),
        ),
    ]
