# Generated by Django 3.2.23 on 2025-07-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_userestriction_data_declaration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseRestriction',
            new_name='UseCondition',
        ),
    ]
