# Generated by Django 3.2.23 on 2025-07-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_add_name_to_contract"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userestriction",
            options={
                "get_latest_by": "added",
                "ordering": ["added"],
                "verbose_name": "Use Condition",
                "verbose_name_plural": "Use Conditions",
            },
        ),
        migrations.AlterField(
            model_name="userestriction",
            name="data_declaration",
            field=models.ForeignKey(
                help_text="The data declaration to which this condition applies.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_use_restrictions",
                to="core.datadeclaration",
            ),
        ),
        migrations.AlterField(
            model_name="userestriction",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Provide a free text description of the condition.",
                null=True,
                verbose_name="Use Condition note",
            ),
        ),
        migrations.AlterField(
            model_name="userestriction",
            name="restriction_class",
            field=models.CharField(
                blank=True,
                help_text="Select the GA4GH code for the condition.  Refer to 'GA4GH Consent Codes' for a detailed explanation of each.",
                max_length=20,
                null=True,
                verbose_name="Use Category",
            ),
        ),
        migrations.AlterField(
            model_name="userestriction",
            name="use_class_note",
            field=models.TextField(
                blank=True,
                help_text="A question asked when collecting the condition class",
                max_length=255,
                null=True,
                verbose_name="Use Category note",
            ),
        ),
        migrations.AlterField(
            model_name="userestriction",
            name="use_restriction_rule",
            field=models.TextField(
                choices=[
                    ("PROHIBITION", "PROHIBITION"),
                    ("OBLIGATION", "OBLIGATION"),
                    ("PERMISSION", "PERMISSION"),
                    ("CONSTRAINED_PERMISSION", "CONSTRAINED_PERMISSION"),
                ],
                default="PROHIBITION",
                max_length=64,
                verbose_name="Use Condition Rule",
            ),
        ),
    ]
