# Generated by Django 3.2.23 on 2025-07-01 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_update_userestriction_verbose_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userestriction",
            name="data_declaration",
            field=models.ForeignKey(
                help_text="The data declaration to which this condition applies.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_use_conditions",
                to="core.datadeclaration",
            ),
        ),
    ]
