# Generated by Django 3.2.23 on 2025-07-14 16:28

import core.models.data_declaration
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_add_name_to_contract"),
    ]

    operations = [
        migrations.CreateModel(
            name="DAC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the Data Access Committee.",
                        max_length=255,
                        unique=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the DAC's purpose and scope.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="The contract under which this Data Access Committee operates.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dac",
                        to="core.contract",
                        verbose_name="Contract",
                    ),
                ),
                (
                    "local_custodians",
                    models.ManyToManyField(
                        help_text="Local custodians are the members of the DAC who are responsible for managing data access requests.",
                        related_name="dac_custodians",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Local custodians",
                    ),
                ),
            ],
            options={
                "ordering": ["added"],
                "permissions": [
                    ("protected_dac", "Can edit PROTECTED elements of DAC instances"),
                    ("admin_dac", "Can edit permissions on DAC instances"),
                ],
                "get_latest_by": "added",
            },
        ),
        migrations.CreateModel(
            name="DacMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("remark", models.CharField(max_length=255)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.contact"
                    ),
                ),
                (
                    "dac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.dac"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dac",
            name="members",
            field=models.ManyToManyField(
                blank=True, through="core.DacMembership", to="core.Contact"
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="dac",
            field=models.ForeignKey(
                blank=True,
                help_text="Data Access Committee (DAC) is responsible for reviewing and approving data access requests for this dataset.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datasets",
                to="core.dac",
                verbose_name="Data Access Committee",
            ),
        ),
        migrations.AddConstraint(
            model_name="dacmembership",
            constraint=models.UniqueConstraint(
                fields=("contact", "dac"), name="unique_person_group"
            ),
        ),
    ]
