# Generated by Django 3.2.23 on 2025-07-01 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_rename_userestriction_usecondition"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RestrictionClass",
            new_name="ConditionClass",
        ),
    ]
