# Generated by Django 3.2.23 on 2025-07-16 10:17

import core.models.data_declaration
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_auto_20250714_1828"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conditionclass",
            options={
                "get_latest_by": "added",
                "ordering": ["name"],
                "verbose_name": "Condition Class",
                "verbose_name_plural": "Condition Classes",
            },
        ),
        migrations.AlterField(
            model_name="datadeclaration",
            name="consent_status",
            field=enumchoicefield.fields.EnumChoiceField(
                default=core.models.data_declaration.ConsentStatus(1),
                enum_class=core.models.data_declaration.ConsentStatus,
                help_text="Is the consent given by data subjects heterogeneous or homogeneous. Homogeneous consent  means that all subjects' data have the same conditions. Heterogeneous means that there are differences among consents given by subjects, therefore  there are differing use conditions on data.",
                max_length=13,
            ),
        ),
    ]
