# Generated by Django 5.2.6 on 2026-02-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_auto_20250716_1217"),
    ]

    operations = [
        migrations.AddField(
            model_name="exposure",
            name="request_pdf_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Adds a PDF of the request to REMS remarks.",
                verbose_name="Attach request as PDF",
            ),
        ),
    ]
