# Generated by Django 5.2.8 on 2026-05-21 14:35

import core.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_exposure_request_pdf_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.FileField(
                max_length=255, upload_to=core.models.document.get_file_name
            ),
        ),
    ]
