# Generated by Django 2.1.9 on 2019-08-02 12:33

from django.db import migrations
import enumchoicefield.fields
import notification.models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=enumchoicefield.fields.EnumChoiceField(enum_class=notification.models.NotificationVerb, max_length=19),
        ),
    ]
