# Generated by Django 3.2 on 2022-07-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0002_auto_20190802_1433"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="notificationsetting",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
