# Generated by Django 3.2.20 on 2023-10-25 09:00

from django.db import migrations, models, connection
import enumchoicefield.fields
import notification.models


def empty_notification_table(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("TRUNCATE TABLE notification_notification;")


def rollback_empty_notification_table(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0003_auto_20220726_1343"),
    ]

    operations = [
        migrations.RunPython(
            empty_notification_table, rollback_empty_notification_table
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="actor",
            new_name="recipient",
        ),
        migrations.RemoveField(
            model_name="notificationsetting",
            name="style",
        ),
        migrations.AddField(
            model_name="notification",
            name="dismissed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="dispatch_by_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="dispatch_in_app",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="notification",
            name="on",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="processing_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="notificationsetting",
            name="notification_offset",
            field=models.PositiveSmallIntegerField(
                default=90,
                help_text="Define how many days before the actual event you want to receive the notification",
                verbose_name="Notification time",
            ),
        ),
        migrations.AddField(
            model_name="notificationsetting",
            name="send_email",
            field=models.BooleanField(
                default=False,
                help_text="Notifications will be send directly to your email. See your [profile page] for more detail.",
            ),
        ),
        migrations.AddField(
            model_name="notificationsetting",
            name="send_in_app",
            field=models.BooleanField(
                default=True,
                help_text="Notification will be displayed in DAISY interface",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=enumchoicefield.fields.EnumChoiceField(
                enum_class=notification.models.NotificationVerb, max_length=13
            ),
        ),
    ]
