---
- name: Install gunicorn
  pip:
    name: gunicorn
    executable: /usr/local/bin/pip3
    state: present


- name: Create gunicorn.service file
  ansible.builtin.template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service


- name: Enable Gunicorn service
  systemd:
    name: gunicorn
    state: started
    enabled: yes