- name: Install dependencies
  dnf:
    name: 
      - socat
      - logrotate
    state: present

- name: Import Erlang/RabbitMQ keys
  rpm_key: 
    state: present
    key: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc

- name: Remove existing erlang installation
  dnf:
    name: erlang
    state: absent

- name: Get erlang package
  get_url:
    url: https://github.com/rabbitmq/erlang-rpm/releases/download/v26.2.5/erlang-26.2.5-1.el8.x86_64.rpm
    dest: /tmp/erlang-26.2.5-1.el8.x86_64.rpm

- name: Install erlang
  dnf:
    name: /tmp/erlang-26.2.5-1.el8.x86_64.rpm
    state: present

- name: Get RabbitMQ server package
  dnf:
    name: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.13.3/rabbitmq-server-3.13.3-1.el8.noarch.rpm
    state: present

# - name: Install RabbitMQ server package
#   shell: dnf install /tmp/rabbitmq-server-3.13.3-1.el8.noarch.rpm -y
#   args:
#     executable: /bin/bash

- name: Start RabbitMQ service
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes