- name: Install dependencies
  dnf:
    name: 
      - socat
      - logrotate
      - erlang
    state: present

- name: Get latest erlang installation script
  get_url:
    url: https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
    dest: /tmp/erlang_script.rpm.sh

- name: Install erlang
  shell: source /tmp/erlang_script.rpm.sh
  args:
    executable: /bin/bash

- name: Install RabbitMQ server package
  dnf:
    name: erlang
    state: present

- name: Get rabbitmq-server key
  shell: rpm --import https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
  args:
    executable: /bin/bash

- name: Get RabbitMQ server package
  get_url:
    url: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.13.3/rabbitmq-server-3.13.3-1.el8.noarch.rpm
    dest: /tmp/rabbitmq-server-3.13.3-1.el8.noarch.rpm

- name: Install RabbitMQ server package
  shell: dnf install /tmp/rabbitmq-server-3.13.3-1.el8.noarch.rpm -y
  args:
    executable: /bin/bash

- name: Start RabbitMQ service
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes