- name: Add user
  user:
    name: '{{ daisy_user }}'
    state: present

- name: Add user to the 'users' group
  user:
    name: '{{ daisy_user }}'
    groups: users
    append: yes

- name: Create directories 'config' and 'log'
  file:
    path: /home/{{ daisy_user }}/{{ item }}
    state: directory
    owner: '{{ daisy_user }}'
    group: '{{ daisy_user }}'
    recurse: true
  with_items:
    - config
    - log

- name: Clone Daisy repository
  git:
    repo: https://github.com/elixir-luxembourg/daisy.git
    dest: /home/{{ daisy_user }}/daisy

- name: update pip
  pip:
    name: pip
    state: latest

- name: Install Daisy using pip
  pip:
    name: /home/{{ daisy_user }}/daisy/
    extra_args: "--root-user-action ignore"
    editable: true
    state: present
