- name: Install repository
  dnf:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Install PostgreSQL 12
  dnf:
    name: 
      - postgresql12-server
    state: present



- name: Initialize PostgreSQL database
  command: /usr/pgsql-12/bin/postgresql-12-setup initdb 
  changed_when: false

- name: Start PostgreSQL service
  systemd:
    name: postgresql-12
    enabled: yes
    state: started

- name: Create celery.conf for beat
  ansible.builtin.copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/12/data/pg_hba.conf
    owner: postgres
    force: true

- name: Create PostgreSQL user
  postgresql_user:
    db: postgres
    name: "{{ daisy_user }}"
    password: "{{ daisy_db_password }}"
    state: present

- name: Create PostgreSQL database
  postgresql_db:
    name: "{{ daisy_user }}"
    owner: "{{ daisy_user }}"
    state: present

- name: Grant privileges
  postgresql_privs:
    db: "{{ daisy_user }}"
    role: "{{ daisy_user }}"
    priv: ALL
    state: present
