name: Execute the tests

on:
  push:
    branches:
    - use-github-actions
    - master
    - develop
    - dependabot/**
  pull_request:
    branches:
    - develop
    - master

jobs:
  tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Black
      run: pip install black==23.7.0

    - name: Check code formatting with Black
      run: black --check --verbose .

    - name: Prepare DAISY settings for CI
      run: cp elixir_daisy/settings_compose_ci.py elixir_daisy/settings_compose.py

    - name: Build and start containers
      run: docker compose up -d --build

    - name: Install test dependencies
      run: docker compose exec -T --user root web pip install ".[test]"

    - name: Execute the tests
      run: docker compose exec -T web pytest

    - name: Stop containers
      if: always()
      run: docker compose down
