name: Validate Version bump upon release

on:
  release:
    types: [created]

jobs:
  validate-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Validate version in pyproject.toml
      run: |
        # Extract version from pyproject.toml (first matching "version = \"...\"")
        VERSION=$(grep -E '^version\s*=\s*"' pyproject.toml | head -n1 | sed -E 's/.*= *"(.*)".*/\1/')
        echo "Version in pyproject.toml: $VERSION"
        if [[ "v$VERSION" != "$GITHUB_REF_NAME" ]]; then
          echo "Version mismatch: pyproject.toml (v$VERSION) vs release tag ($GITHUB_REF_NAME)"
          exit 1
        fi
