name: Execute the tests

on:
  push:
    branches:
    - master
    - develop
    - dependabot/**
  pull_request:
    branches:
    - develop
    - master

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Copy settings
      run: cp elixir_daisy/settings_compose_ci.py elixir_daisy/settings_compose.py

    - name: Start containers
      run: docker-compose up -d --build

    - name: Run tests
      run: docker-compose exec web python setup.py pytest

    - name: Stop containers
      if: always()
      run: docker-compose down